import type { AppProps } from 'next/app';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<meta charSet='UTF-8' />
				<meta httpEquiv='X-UA-Compatible' content='IE=edge' />
				<meta httpEquiv='Content-Type' content='text/html charset=UTF-8' />
				<meta name='viewport' content='width=device-width, initial-scale=1.0' />
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='./favicon.ico' />
				<meta name='color-scheme' content='light dark' />
				<meta name='supported-color-schemes' content='light dark' />
				<title>Email</title>
			</Head>
			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
